// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKrCwxG9X3uTTXHvskC-SwsRBgMkQslk',
    appId: '1:984837531533:web:990d2703603b611dac7fc4',
    messagingSenderId: '984837531533',
    projectId: 'flutter-prep-cdf94',
    authDomain: 'flutter-prep-cdf94.firebaseapp.com',
    databaseURL: 'https://flutter-prep-cdf94-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-cdf94.firebasestorage.app',
    measurementId: 'G-6K8BGJPJ5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5qib4AwkJ4LeClf9mLnYE7B4FRv5VR4w',
    appId: '1:984837531533:android:6abe828616a98007ac7fc4',
    messagingSenderId: '984837531533',
    projectId: 'flutter-prep-cdf94',
    databaseURL: 'https://flutter-prep-cdf94-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-cdf94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6eqo3VrodMpfsr1my2N1nAG2gITWV7A',
    appId: '1:984837531533:ios:e97920ce268ebd53ac7fc4',
    messagingSenderId: '984837531533',
    projectId: 'flutter-prep-cdf94',
    databaseURL: 'https://flutter-prep-cdf94-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-cdf94.firebasestorage.app',
    iosBundleId: 'com.example.fullCours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf6eqo3VrodMpfsr1my2N1nAG2gITWV7A',
    appId: '1:984837531533:ios:e97920ce268ebd53ac7fc4',
    messagingSenderId: '984837531533',
    projectId: 'flutter-prep-cdf94',
    databaseURL: 'https://flutter-prep-cdf94-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-cdf94.firebasestorage.app',
    iosBundleId: 'com.example.fullCours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCKrCwxG9X3uTTXHvskC-SwsRBgMkQslk',
    appId: '1:984837531533:web:7f9a1a886b6ab776ac7fc4',
    messagingSenderId: '984837531533',
    projectId: 'flutter-prep-cdf94',
    authDomain: 'flutter-prep-cdf94.firebaseapp.com',
    databaseURL: 'https://flutter-prep-cdf94-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-cdf94.firebasestorage.app',
    measurementId: 'G-JWTJ0CHC1G',
  );
}
